<?php

return [
    'messages'=>[
        'addTeam' => 'Team has been saved successfully.',
        'editTeam' => 'Team has been updated successfully.',
        'deleteTeam' => 'Team has been deleted successfully.',
        'teamNotExists' => 'Team does not exist.',
        'addPlayer' => 'Player has been saved.',
        'editPlayer' => 'Player has been updated.',
        'playerNotExists' => 'Player does not exist.',
        'playerAlreadyInTeam' => 'Player already exists in team.',
        'playerAlreadyInOtherTeam' => 'Player already exists in other team.',
        'playerAssigned' => 'Player assigned to team successfully.',
        'playerNotExistsInTeam' => 'Player does not exists in team.',
        'playerRemoved' => 'Player removed from team successfully.',
        'twoTeamsCanNotBeSame' => 'Both team are same..please enter different team.',
        'winnerRule' => "Winner field can have only one from 'teamOne' or 'teamTwo' or 'draw' as valid values",
        'matchSaved' => 'Match saved successfully.',
        'teamOne' => 'teamOne',
        'teamTwo' => 'teamTwo',
        'draw' => 'draw',
        'won' => 'Won',
        'lost'=> 'Lost',
        'drawn' => 'Drawn',
        'duplicateTeam' => 'Please select different team.',
        'fill_team_name' => 'Please fill team name.',
        'fill_state_name' => 'Please fill club state name.',
        'fill_first_name' => 'Please fill first name.',
        'fill_last_name' => 'Please fill last name.',
        'fill_jersy_no' => 'Please fill jersy number.',
        'fill_country_name' => 'Please fill country name.',
        'fill_matches' => 'Please fill number of matches.',
        'fill_run' => 'Please fill run scored.',
        'fill_high_score' => 'Please fill highest score.',
        'fill_fifties' => 'Please fill number of fifties.',
        'fill_hundred' => 'Please fill number of hundred.',
        'upload_logo' => 'Please upload Company Logo.',
        'upload_image' => 'Please upload Player Image.',
        'valid-image' => 'Please upload valid image.',
    ],
];

